//
// Created by David on 28/10/2021.
//

#ifndef DESIGNPRINCIPLES_DEPENDANCYINVERSIONPRINC_H
#define DESIGNPRINCIPLES_DEPENDANCYINVERSIONPRINC_H


class DependancyInversionPrinc {

};


#endif //DESIGNPRINCIPLES_DEPENDANCYINVERSIONPRINC_H
